name: CodSpeed

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # for OpenID Connect authentication with CodSpeed

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      # The Rust toolchain is read from rust-toolchain.toml.
      - name: Setup Rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1.3.0
        with:
          cache-target: release
          bins: cargo-codspeed

      - name: Build the benchmark targets
        run: cargo codspeed build -m simulation -p ironrdp-bench -p ironrdp-bulk

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v5.2.1
        with:
          mode: simulation
          run: cargo codspeed run
